-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid,
  user_id uuid,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid,
  old_data jsonb,
  new_data jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT audit_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.contracts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid,
  task_id uuid,
  project_id uuid,
  template_type text NOT NULL,
  status USER-DEFINED DEFAULT 'draft'::contract_status,
  party_a_id uuid NOT NULL,
  party_b_id uuid,
  party_b_email text,
  terms jsonb NOT NULL,
  party_a_signed_at timestamp with time zone,
  party_b_signed_at timestamp with time zone,
  pdf_path text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contracts_pkey PRIMARY KEY (id),
  CONSTRAINT contracts_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT contracts_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id),
  CONSTRAINT contracts_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT contracts_party_a_id_fkey FOREIGN KEY (party_a_id) REFERENCES public.users(id),
  CONSTRAINT contracts_party_b_id_fkey FOREIGN KEY (party_b_id) REFERENCES public.users(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  settings jsonb DEFAULT '{}'::jsonb,
  default_r numeric DEFAULT 0.7,
  r_bounds jsonb DEFAULT '{"max": 0.9, "min": 0.5}'::jsonb,
  qc_beta numeric DEFAULT 0.25,
  qc_gamma numeric DEFAULT 0.4,
  pm_x numeric DEFAULT 0.5,
  pm_overdraft_penalty numeric DEFAULT 1.5,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid,
  user_id uuid,
  task_id uuid,
  project_id uuid,
  qc_review_id uuid,
  payout_type text NOT NULL,
  gross_amount numeric NOT NULL,
  deductions numeric DEFAULT 0,
  net_amount numeric NOT NULL,
  calculation_details jsonb,
  status text DEFAULT 'pending'::text,
  paid_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payouts_pkey PRIMARY KEY (id),
  CONSTRAINT payouts_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT payouts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT payouts_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id),
  CONSTRAINT payouts_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT payouts_qc_review_id_fkey FOREIGN KEY (qc_review_id) REFERENCES public.qc_reviews(id)
);
CREATE TABLE public.projects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid,
  name text NOT NULL,
  description text,
  status USER-DEFINED DEFAULT 'draft'::project_status,
  total_value numeric NOT NULL,
  story_points_budget integer,
  spent numeric DEFAULT 0,
  sales_id uuid,
  pm_id uuid,
  deadline timestamp with time zone,
  pm_bonus numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  picked_up_at timestamp with time zone,
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT projects_sales_id_fkey FOREIGN KEY (sales_id) REFERENCES public.users(id),
  CONSTRAINT projects_pm_id_fkey FOREIGN KEY (pm_id) REFERENCES public.users(id)
);
CREATE TABLE public.qc_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  task_id uuid,
  review_type USER-DEFINED NOT NULL,
  reviewer_id uuid,
  passed boolean,
  confidence numeric,
  feedback text,
  v0 numeric,
  d_k numeric,
  pass_number integer DEFAULT 1,
  weight numeric DEFAULT 1.0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT qc_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT qc_reviews_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id),
  CONSTRAINT qc_reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.users(id)
);
CREATE TABLE public.tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid,
  project_id uuid,
  title text NOT NULL,
  description text,
  status USER-DEFINED DEFAULT 'open'::task_status,
  story_points integer,
  dollar_value numeric NOT NULL,
  assignee_id uuid,
  assigned_at timestamp with time zone,
  deadline timestamp with time zone,
  completed_at timestamp with time zone,
  urgency_multiplier numeric DEFAULT 1.0,
  required_level integer DEFAULT 1,
  submission_data jsonb,
  submission_files ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT tasks_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT tasks_assignee_id_fkey FOREIGN KEY (assignee_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  auth_id uuid,
  org_id uuid,
  email text NOT NULL,
  full_name text,
  role USER-DEFINED NOT NULL DEFAULT 'employee'::user_role,
  base_salary numeric,
  r numeric,
  level integer DEFAULT 1,
  training_level integer DEFAULT 1,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_auth_id_fkey FOREIGN KEY (auth_id) REFERENCES auth.users(id),
  CONSTRAINT users_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);